theme: jekyll-theme-minimal
title: Polenhive's homepage
description: This site is a collection of my projects. It serves as a personal portfolio and a platform to share my work with the world. 
author: Paula García Reynoso
